spring:
  application:
    name: simple-discovery-server
server:
  port: 8761
eureka:  
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
info:
  artifactId: "@project.artifactId@"
  description: "@project.description@"
  version: "@project.version@"
    