spring:
  application:
    name: simple-discovery-server
  cloud:
    config:
      uri: http://localhost:8888
server:
  port: 8761
#eureka:
#  client:
#    fetch-registry: false
#eureka:
#  client:
#    register-with-eureka: false
